# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib vellum, .registration = TRUE
NULL

#' Backend identity and build info (internal diagnostic).
rs_backend_info <- function() .Call(wrap__rs_backend_info)

rs_aggregate_2d <- function(x, y, w, nx, ny, x0, x1, y0, y1) .Call(wrap__rs_aggregate_2d, x, y, w, nx, ny, x0, x1, y0, y1)

rs_attractor <- function(kind, n, a, b, c, d, x0, y0) .Call(wrap__rs_attractor, kind, n, a, b, c, d, x0, y0)

#' A drawing scene held in the Rust backend. Internal: the public R API is the
#' S7 layer (`vl_scene()`, grobs, `render()`), which compiles to this object.
#'
#' @section Methods:
#'\subsection{Method `new`}{
#'Create a scene `width` x `height` inches at `dpi`, with background `bg`
#'(a length-4 integer RGBA vector). A root viewport covering the whole page
#'(npc == native) is created as viewport 0.
#'}
#'
#'\subsection{Method `push_viewport`}{
#'Push a viewport as a child of the current one and make it current.
#'Returns the new viewport's id. If `lrow`/`lcol` are >= 0 the viewport is
#'placed into that (0-based) cell of the parent's layout; otherwise it is
#'placed by centre/size in parent coordinates.
#'}
#'
#'\subsection{Method `set_clip_path`}{
#'Attach an arbitrary clip path (in the current viewport's coordinates) to
#'the current viewport; `nper` gives the point count of each closed sub-path.
#'}
#'
#'\subsection{Method `pop_viewport`}{
#'Move the cursor up `n` levels (towards the root). Stops at the root.
#'}
#'
#'\subsection{Method `to_root`}{
#'Move the cursor to the root viewport.
#'}
#'
#'\subsection{Method `set_layout`}{
#'Attach a row/column layout to the current viewport. Tracks are given as
#'parallel value + unit-code vectors; the unit `"null"` marks a flexible
#'track whose value is its weight.
#'}
#'
#'\subsection{Method `rects`}{
#'A whole batch of rectangles in one call, sharing one gpar. Coordinates and
#'per-coordinate unit codes are parallel slices.
#'}
#'
#'\subsection{Method `circles`}{
#'A whole batch of circles in one call, sharing one gpar (also used for
#'`points`, with the radius carrying the marker size).
#'}
#'
#'\subsection{Method `markers`}{
#'A batch of markers (point glyphs) sharing one gpar. Like `circles` but each
#'element carries a `shape` code (0 circle, 1 square, 2 triangle, 3 diamond,
#'4 plus, 5 cross); `size` is the marker radius. Filled shapes fill+stroke per
#'gpar; plus/cross are stroke-only. (circle_grob / default points use the
#'faster `circles` path; this is for shape variety.)
#'}
#'
#'\subsection{Method `segments`}{
#'A batch of disjoint line segments (stroke only), sharing one gpar.
#'}
#'
#'\subsection{Method `path`}{
#'A general path. `nper` gives the number of points in each closed sub-path
#'(so holes are sub-paths under the even-odd or winding rule).
#'}
#'
#'\subsection{Method `image`}{
#'A raster image: `rgba` is a flat straight-RGBA integer vector (`iw` x `ih`,
#'top-left, 4 per pixel), drawn into a `w` x `h` cell centred at `(x, y)`.
#'}
#'
#'\subsection{Method `text`}{
#'Add pre-shaped text. The R wrapper does shaping (via `textshaping`) and
#'passes per-glyph ids/positions/fonts plus the block size.
#'}
#'
#'\subsection{Method `texts`}{
#'Add a whole batch of pre-shaped text labels in one call (one shaping pass
#'on the R side, one FFI here). Glyphs are flat across all labels, split by
#'`nper` (glyph count per label); positions/sizes/rot/labels are per-label;
#'font + just + colour are shared.
#'}
#'
#'\subsection{Method `mask_begin`}{
#'Begin collecting a mask's content for the current viewport. Until the
#'matching `mask_end`, primitives are routed into the mask instead of the
#'drawn scene. `kind` is 0 (alpha) or 1 (luminance). Returns its index.
#'}
#'
#'\subsection{Method `mask_end`}{
#'Stop routing primitives into the most recent mask.
#'}
#'
#'\subsection{Method `group_start`}{
#'Open an isolated compositing group. Routed through `emit_node` so a group
#'nested inside a mask (a mask grob that itself masks a viewport) lands in
#'the same node list as its content, keeping markers and content in sync.
#'}
#'
#'\subsection{Method `group_end`}{
#'Close the group, compositing it through mask index `mask` (negative = no
#'mask, just isolation).
#'}
#'
#'\subsection{Method `len`}{
#'Number of primitives currently in the scene.
#'}
#'
#'\subsection{Method `dim`}{
#'Device dimensions in pixels, `c(width, height)`.
#'}
#'
#'\subsection{Method `dpi`}{
#'Device resolution in dots per inch.
#'}
#'
#'\subsection{Method `render_png`}{
#'Render the scene to a PNG file.
#'}
#'
#'\subsection{Method `render_svg`}{
#'Render the scene to an SVG file.
#'}
#'
#'\subsection{Method `render_pdf`}{
#'Render the scene to a PDF file.
#'}
#'
#'\subsection{Method `rgba`}{
#'Render and return the whole image as row-major RGBA bytes
#'`[r, g, b, a, ...]` (top-left origin, x fastest).
#'}
#'
#'\subsection{Method `content_bbox`}{
#'Render and return the tight bounding box of non-transparent content as
#'`c(min_x, min_y, max_x, max_y)` (device px, inclusive), or an empty vector
#'if nothing was drawn. Used to measure a grob's extent (grobwidth/height).
#'}
#'
#'\subsection{Method `pixel`}{
#'Render and return the RGBA of device pixel `(x, y)` as `c(r, g, b, a)`.
#'}
#'
Scene <- new.env(parent = emptyenv())

Scene$new <- function(width, height, dpi, bg) .Call(wrap__Scene__new, width, height, dpi, bg)

Scene$push_viewport <- function(cx, cy, w, h, cxu, cyu, wu, hu, xscale, yscale, angle, clip, lrow, lcol, lrowspan, lcolspan, fill, col, lwd, alpha, stroke) .Call(wrap__Scene__push_viewport, self, cx, cy, w, h, cxu, cyu, wu, hu, xscale, yscale, angle, clip, lrow, lcol, lrowspan, lcolspan, fill, col, lwd, alpha, stroke)

Scene$set_clip_path <- function(x, y, xu, yu, nper, evenodd) .Call(wrap__Scene__set_clip_path, self, x, y, xu, yu, nper, evenodd)

Scene$pop_viewport <- function(n) .Call(wrap__Scene__pop_viewport, self, n)

Scene$to_root <- function() .Call(wrap__Scene__to_root, self)

Scene$set_layout <- function(wvals, wunits, hvals, hunits) .Call(wrap__Scene__set_layout, self, wvals, wunits, hvals, hunits)

Scene$rect <- function(x, y, w, h, xu, yu, wu, hu, fill, col, lwd, alpha, stroke) .Call(wrap__Scene__rect, self, x, y, w, h, xu, yu, wu, hu, fill, col, lwd, alpha, stroke)

Scene$lines <- function(x, y, xu, yu, col, lwd, alpha, stroke, aangle, alen, aends, aclosed) .Call(wrap__Scene__lines, self, x, y, xu, yu, col, lwd, alpha, stroke, aangle, alen, aends, aclosed)

Scene$polygon <- function(x, y, xu, yu, fill, col, lwd, alpha, stroke) .Call(wrap__Scene__polygon, self, x, y, xu, yu, fill, col, lwd, alpha, stroke)

Scene$circle <- function(x, y, r, xu, yu, ru, fill, col, lwd, alpha, stroke) .Call(wrap__Scene__circle, self, x, y, r, xu, yu, ru, fill, col, lwd, alpha, stroke)

Scene$rects <- function(x, y, w, h, xu, yu, wu, hu, fill, col, lwd, alpha, stroke) .Call(wrap__Scene__rects, self, x, y, w, h, xu, yu, wu, hu, fill, col, lwd, alpha, stroke)

Scene$circles <- function(x, y, r, xu, yu, ru, fill, col, lwd, alpha, stroke) .Call(wrap__Scene__circles, self, x, y, r, xu, yu, ru, fill, col, lwd, alpha, stroke)

Scene$markers <- function(x, y, size, xu, yu, su, shape, fill, col, lwd, alpha, stroke) .Call(wrap__Scene__markers, self, x, y, size, xu, yu, su, shape, fill, col, lwd, alpha, stroke)

Scene$segments <- function(x0, y0, x1, y1, x0u, y0u, x1u, y1u, col, lwd, alpha, stroke, aangle, alen, aends, aclosed) .Call(wrap__Scene__segments, self, x0, y0, x1, y1, x0u, y0u, x1u, y1u, col, lwd, alpha, stroke, aangle, alen, aends, aclosed)

Scene$path <- function(x, y, xu, yu, nper, evenodd, fill, col, lwd, alpha, stroke) .Call(wrap__Scene__path, self, x, y, xu, yu, nper, evenodd, fill, col, lwd, alpha, stroke)

Scene$image <- function(rgba, iw, ih, x, y, w, h, xu, yu, wu, hu, interpolate) .Call(wrap__Scene__image, self, rgba, iw, ih, x, y, w, h, xu, yu, wu, hu, interpolate)

Scene$text <- function(x, y, xu, yu, rot, hjust, vjust, w, h, gid, gx, gy, gsize, gpath, gface, label, family, face, size, col, alpha) .Call(wrap__Scene__text, self, x, y, xu, yu, rot, hjust, vjust, w, h, gid, gx, gy, gsize, gpath, gface, label, family, face, size, col, alpha)

Scene$texts <- function(x, y, xu, yu, rot, hjust, vjust, w, h, nper, gid, gx, gy, gsize, gpath, gface, label, family, face, size, col, alpha) .Call(wrap__Scene__texts, self, x, y, xu, yu, rot, hjust, vjust, w, h, nper, gid, gx, gy, gsize, gpath, gface, label, family, face, size, col, alpha)

Scene$mask_begin <- function(kind) .Call(wrap__Scene__mask_begin, self, kind)

Scene$mask_end <- function() .Call(wrap__Scene__mask_end, self)

Scene$group_start <- function() .Call(wrap__Scene__group_start, self)

Scene$group_end <- function(mask) .Call(wrap__Scene__group_end, self, mask)

Scene$len <- function() .Call(wrap__Scene__len, self)

Scene$dim <- function() .Call(wrap__Scene__dim, self)

Scene$dpi <- function() .Call(wrap__Scene__dpi, self)

Scene$render_png <- function(path) .Call(wrap__Scene__render_png, self, path)

Scene$render_svg <- function(path) .Call(wrap__Scene__render_svg, self, path)

Scene$render_pdf <- function(path) .Call(wrap__Scene__render_pdf, self, path)

Scene$rgba <- function() .Call(wrap__Scene__rgba, self)

Scene$content_bbox <- function() .Call(wrap__Scene__content_bbox, self)

Scene$pixel <- function(x, y) .Call(wrap__Scene__pixel, self, x, y)

#' @export
`$.Scene` <- function (self, name) { func <- Scene[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Scene` <- `$.Scene`

# nolint end
