# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib vellum, .registration = TRUE
NULL

#' Backend identity and build info (internal diagnostic).
rs_backend_info <- function() .Call(wrap__rs_backend_info)

#' Empty the persistent glyph-outline cache (font bytes + extracted outlines).
rs_clear_glyph_cache <- function() .Call(wrap__rs_clear_glyph_cache)

#' Empty the repaint-boundary sub-raster cache (FW4c) and reset its counters.
rs_clear_subraster_cache <- function() .Call(wrap__rs_clear_subraster_cache)

#' Sub-raster cache stats: `c(hits, misses, resident_entries)` (tests/diagnostics).
rs_subraster_stats <- function() .Call(wrap__rs_subraster_stats)

#' Set the glyph-bitmap cache mode.
#' @param mode Integer: 0 = off, 1 = auto (threshold), 2 = on.
#' @keywords internal
rs_set_glyph_bitmap_mode <- function(mode) .Call(wrap__rs_set_glyph_bitmap_mode, mode)

#' Glyph sprite cache stats: `c(hits, misses, resident)` (tests/diagnostics).
rs_glyph_sprite_stats <- function() .Call(wrap__rs_glyph_sprite_stats)

rs_aggregate_2d <- function(x, y, w, nx, ny, x0, x1, y0, y1) .Call(wrap__rs_aggregate_2d, x, y, w, nx, ny, x0, x1, y0, y1)

rs_attractor <- function(kind, n, a, b, c, d, x0, y0) .Call(wrap__rs_attractor, kind, n, a, b, c, d, x0, y0)

#' A drawing scene held in the Rust backend. Internal: the public R API is the
#' S7 layer (`vl_scene()`, grobs, `render()`), which compiles to this object.
#'
#' @section Methods:
#'\subsection{Method `new`}{
#'Create a scene `width` x `height` inches at `dpi`, with background `bg`
#'(a length-4 integer RGBA vector). A root viewport covering the whole page
#'(npc == native) is created as viewport 0.
#'}
#'
#'\subsection{Method `set_a11y`}{
#'Set the scene-level accessible name / description (a11y). Emitted by the
#'SVG backend (`role="img"` + `<title>`/`<desc>`) and the tagged-PDF path.
#'`prefix` uniquifies the SVG `<title>`/`<desc>` ids across a page.
#'}
#'
#'\subsection{Method `want_bitmap_text`}{
#'Whether the page backend should enable the glyph-bitmap fast path for this
#'render: mode 2 (on) always, mode 1 (auto) above the glyph threshold, mode 0
#'(off) never. Read from the thread-local mode set by R per render.
#'}
#'
#'\subsection{Method `set_pick`}{
#'Set the hit-test pick id applied to subsequently-emitted primitives (one
#'per grob; the R side assigns ids in paint order). See `hit_test`.
#'}
#'
#'\subsection{Method `set_meta`}{
#'Set the semantic metadata applied to subsequently-emitted primitives (one
#'per grob). Empty strings clear a field. Emitted by vector backends.
#'}
#'
#'\subsection{Method `push_viewport`}{
#'Push a viewport as a child of the current one and make it current.
#'Returns the new viewport's id. If `lrow`/`lcol` are >= 0 the viewport is
#'placed into that (0-based) cell of the parent's layout; otherwise it is
#'placed by centre/size in parent coordinates.
#'}
#'
#'\subsection{Method `set_clip_path`}{
#'Attach an arbitrary clip path (in the current viewport's coordinates) to
#'the current viewport; `nper` gives the point count of each closed sub-path.
#'}
#'
#'\subsection{Method `pop_viewport`}{
#'Move the cursor up `n` levels (towards the root). Stops at the root.
#'}
#'
#'\subsection{Method `to_root`}{
#'Move the cursor to the root viewport.
#'}
#'
#'\subsection{Method `set_layout`}{
#'Attach a row/column layout to the current viewport. Tracks are given as
#'parallel value + unit-code vectors; the unit `"null"` marks a flexible
#'track whose value is its weight. `respect` enables grid-style aspect
#'locking (equal physical size for a `null` width unit and a `null` height
#'unit; see `solve_layout`).
#'}
#'
#'\subsection{Method `rects`}{
#'A whole batch of rectangles in one call, sharing one gpar. Coordinates and
#'per-coordinate unit codes are parallel slices.
#'}
#'
#'\subsection{Method `circles`}{
#'A whole batch of circles in one call, sharing one gpar (also used for
#'`points`, with the radius carrying the marker size).
#'}
#'
#'\subsection{Method `markers`}{
#'A batch of markers (point glyphs) sharing one gpar. Like `circles` but each
#'element carries a `shape` code (0 circle, 1 square, 2 triangle, 3 diamond,
#'4 plus, 5 cross); `size` is the marker radius. Filled shapes fill+stroke per
#'gpar; plus/cross are stroke-only. (circle_grob / default points use the
#'faster `circles` path; this is for shape variety.)
#'}
#'
#'\subsection{Method `hexagons`}{
#'A batch of hexagons for hex-binning. `flat` picks flat-top vs pointy-top;
#'`fill` is a flat per-hex RGBA stream (`[r,g,b,a, r,g,b,a, ...]`, one quad per
#'hex); `col`/`lwd`/`alpha`/`stroke` give the *uniform* stroke (the gpar's fill
#'is unused — fill is per element). Geometry: if `w`/`h` are empty each hex is
#'regular with circumradius `size`; otherwise `w`/`h` are the per-hex full
#'width/height (corner-to-corner along each axis), resolved per-axis so a hex
#'can tile a non-square lattice, and `size` is ignored.
#'}
#'
#'\subsection{Method `sectors`}{
#'A batch of annular sectors (pie/donut/rose wedges). `(x,y)` is the centre,
#'`r0`/`r1` the inner/outer radius, `theta0`/`theta1` the start/end angle in
#'**radians** (0 at 3 o'clock, CCW). `fill` is a flat per-sector RGBA stream
#'(one quad per sector, like `hexagons`); `col`/`lwd`/`alpha`/`stroke` give the
#'uniform stroke. `r0=0` ⇒ pie slice; `r0=r1` ⇒ an arc outline (no fill).
#'}
#'
#'\subsection{Method `segments`}{
#'A batch of disjoint line segments (stroke only), sharing one gpar.
#'}
#'
#'\subsection{Method `add_loop`}{
#'A batch of self-loops (cubic-Bézier teardrops). See `Node::Loop`.
#'}
#'
#'\subsection{Method `path`}{
#'A general path. `nper` gives the number of points in each closed sub-path
#'(so holes are sub-paths under the even-odd or winding rule).
#'}
#'
#'\subsection{Method `image`}{
#'A raster image: `rgba` is a flat straight-RGBA integer vector (`iw` x `ih`,
#'top-left, 4 per pixel), drawn into a `w` x `h` cell centred at `(x, y)`.
#'}
#'
#'\subsection{Method `text`}{
#'Add pre-shaped text. The R wrapper does shaping (via `textshaping`) and
#'passes per-glyph ids/positions/fonts plus the block size.
#'}
#'
#'\subsection{Method `texts`}{
#'Add a whole batch of pre-shaped text labels in one call (one shaping pass
#'on the R side, one FFI here). Glyphs are flat across all labels, split by
#'`nper` (glyph count per label); positions/sizes/rot/labels are per-label;
#'font + just + colour are shared.
#'}
#'
#'\subsection{Method `texts_rich`}{
#'Like `texts`, but with a **per-glyph** fill colour stream (`gcol`, a flat RGBA
#'int stream, 4 ints per glyph, parallel to the glyph arrays). Used by rich
#'(multi-run) labels where colour varies within a single label. Everything else
#'matches `texts`; the shared `col` becomes the fallback only when a glyph's
#'colour is absent (it never is here, but keeps the gpar resolve consistent).
#'}
#'
#'\subsection{Method `mask_begin`}{
#'Begin collecting a mask's content for the current viewport. Until the
#'matching `mask_end`, primitives are routed into the mask instead of the
#'drawn scene. `kind` is 0 (alpha) or 1 (luminance). Returns its index.
#'}
#'
#'\subsection{Method `mask_end`}{
#'Stop routing primitives into the most recent mask.
#'}
#'
#'\subsection{Method `group_start`}{
#'Open an isolated compositing group, modulated by mask index `mask`
#'(negative = no mask, just isolation), group opacity `alpha`, and blend mode
#'`blend` (a code; 0 = normal). Routed through `emit_node` so a group nested
#'inside a mask (a mask grob that itself masks a viewport) lands in the same
#'node list as its content, keeping markers and content in sync.
#'}
#'
#'\subsection{Method `group_end`}{
#'Close the most recently opened group.
#'}
#'
#'\subsection{Method `begin_panel`}{
#'Open a named panel group around the following nodes (paired with
#'`end_panel`). The SVG backend wraps them in `<g data-vellum-panel="name">`;
#'other backends ignore it. Emitted by the R compiler for named viewports.
#'}
#'
#'\subsection{Method `end_panel`}{
#'Close the most recently opened panel group.
#'}
#'
#'\subsection{Method `subraster_start`}{
#'Open a repaint boundary for the current subtree, tagged with content id
#'`nid` (a per-subtree token from R). See `Node::SubrasterStart`.
#'}
#'
#'\subsection{Method `subraster_end`}{
#'Close the most recently opened repaint boundary.
#'}
#'
#'\subsection{Method `len`}{
#'Number of primitives currently in the scene.
#'}
#'
#'\subsection{Method `dim`}{
#'Device dimensions in pixels, `c(width, height)`.
#'}
#'
#'\subsection{Method `dpi`}{
#'Device resolution in dots per inch.
#'}
#'
#'\subsection{Method `render_png`}{
#'Render the scene to a PNG file. Returns any degradation warnings (none for
#'the raster backend today; uniform with the SVG/PDF signatures).
#'}
#'
#'\subsection{Method `render_svg`}{
#'Render the scene to an SVG file. `outline_text` emits glyph outlines
#'instead of selectable `<text>` (pixel-faithful, matches raster/PDF).
#'Returns any degradation warnings.
#'}
#'
#'\subsection{Method `render_svg_string`}{
#'Render the scene and return the SVG document as a string (rather than
#'writing it to a file). Same output as `render_svg`; the interactivity
#'layer needs the markup in-memory to embed it in an htmlwidget, and tests
#'use it to assert on emitted attributes. Degradation warnings are dropped
#'here (the file path surfaces them); callers wanting them use `render_svg`.
#'}
#'
#'\subsection{Method `render_pdf`}{
#'Render the scene to a PDF file. Returns any degradation warnings (e.g. a
#'tiling pattern or mask the PDF walk could not honour).
#'}
#'
#'\subsection{Method `rgba`}{
#'Render and return the whole image as row-major RGBA bytes
#'`[r, g, b, a, ...]` (top-left origin, x fastest).
#'}
#'
#'\subsection{Method `content_bbox`}{
#'Render and return the tight bounding box of non-transparent content as
#'`c(min_x, min_y, max_x, max_y)` (device px, inclusive), or an empty vector
#'if nothing was drawn. Used to measure a grob's extent (grobwidth/height).
#'}
#'
#'\subsection{Method `resolved_geometry`}{
#'Resolved per-viewport geometry for the debug overlay / `why_size()`. Runs
#'the layout pass and returns, per viewport (row = viewport id), its parent
#'id, local pixel size, affine transform (`c(sx, ky, kx, sy, tx, ty)` mapping
#'local px -> device px), solved layout track edges (local px, plus the
#'`respect` centering offset), and the device-px bbox of its innermost clip.
#'R joins this with the viewport names it recorded during compilation.
#'}
#'
#'\subsection{Method `element_table`}{
#'Per-element device-px bounding boxes for the batched mark nodes (the ones
#'that can carry data keys): rects, circles, points/markers, hexagons,
#'sectors, segments. Rows are emitted in paint order (the compiler's DFS),
#'one per drawn element — the same order and count the R grammar enumerates,
#'so `scene_model()` zips this with R-side semantics positionally (and
#'cross-checks the `key` column). Columns: `key` ("" = none), enclosing
#'`panel` ("" = none), and device-px bbox `x0,y0,x1,y1` (y-down). Sector boxes
#'use the outer-radius disk and hexagon boxes the circumscribed extent — safe
#'over-approximations sufficient for a spatial index.
#'}
#'
#'\subsection{Method `pixel`}{
#'Render and return the RGBA of device pixel `(x, y)` as `c(r, g, b, a)`.
#'}
#'
#'\subsection{Method `hit_test`}{
#'Hit-test: return the pick id of the topmost primitive covering device pixel
#'`(x, y)`, or -1 if none. Implemented as a colour pick-buffer — each node is
#'drawn opaque (AA off) in a colour encoding its pick id, respecting clips and
#'paint order, then the pixel is decoded — so it is geometry/clip/overlap
#'exact. Markers and text use a bounding box; lines/segments a pick band.
#'}
#'
Scene <- new.env(parent = emptyenv())

Scene$new <- function(width, height, dpi, bg) .Call(wrap__Scene__new, width, height, dpi, bg)

Scene$set_a11y <- function(title, desc, prefix) .Call(wrap__Scene__set_a11y, self, title, desc, prefix)

Scene$want_bitmap_text <- function() .Call(wrap__Scene__want_bitmap_text, self)

Scene$set_pick <- function(id) .Call(wrap__Scene__set_pick, self, id)

Scene$set_meta <- function(id, role, name) .Call(wrap__Scene__set_meta, self, id, role, name)

Scene$push_viewport <- function(cx, cy, w, h, cxu, cxoff, cyu, cyoff, wu, woff, hu, hoff, xscale, yscale, angle, clip, lrow, lcol, lrowspan, lcolspan, fill, col, lwd, alpha, stroke) .Call(wrap__Scene__push_viewport, self, cx, cy, w, h, cxu, cxoff, cyu, cyoff, wu, woff, hu, hoff, xscale, yscale, angle, clip, lrow, lcol, lrowspan, lcolspan, fill, col, lwd, alpha, stroke)

Scene$set_clip_path <- function(x, y, xu, xoff, yu, yoff, nper, evenodd) .Call(wrap__Scene__set_clip_path, self, x, y, xu, xoff, yu, yoff, nper, evenodd)

Scene$pop_viewport <- function(n) .Call(wrap__Scene__pop_viewport, self, n)

Scene$to_root <- function() .Call(wrap__Scene__to_root, self)

Scene$set_layout <- function(wvals, wunits, hvals, hunits, respect) .Call(wrap__Scene__set_layout, self, wvals, wunits, hvals, hunits, respect)

Scene$rect <- function(x, y, w, h, xu, xoff, yu, yoff, wu, woff, hu, hoff, fill, col, lwd, alpha, stroke) .Call(wrap__Scene__rect, self, x, y, w, h, xu, xoff, yu, yoff, wu, woff, hu, hoff, fill, col, lwd, alpha, stroke)

Scene$roundrect <- function(x, y, w, h, r, xu, xoff, yu, yoff, wu, woff, hu, hoff, ru, roff, fill, col, lwd, alpha, stroke, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed) .Call(wrap__Scene__roundrect, self, x, y, w, h, r, xu, xoff, yu, yoff, wu, woff, hu, hoff, ru, roff, fill, col, lwd, alpha, stroke, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed)

Scene$lines <- function(x, y, xu, xoff, yu, yoff, scap, ecap, scapu, ecapu, off, offu, col, lwd, alpha, stroke, aangle, alen, aends, aclosed, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed, key) .Call(wrap__Scene__lines, self, x, y, xu, xoff, yu, yoff, scap, ecap, scapu, ecapu, off, offu, col, lwd, alpha, stroke, aangle, alen, aends, aclosed, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed, key)

Scene$polygon <- function(x, y, xu, xoff, yu, yoff, fill, col, lwd, alpha, stroke, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed, key) .Call(wrap__Scene__polygon, self, x, y, xu, xoff, yu, yoff, fill, col, lwd, alpha, stroke, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed, key)

Scene$circle <- function(x, y, r, xu, xoff, yu, yoff, ru, roff, fill, col, lwd, alpha, stroke) .Call(wrap__Scene__circle, self, x, y, r, xu, xoff, yu, yoff, ru, roff, fill, col, lwd, alpha, stroke)

Scene$rects <- function(x, y, w, h, xu, xoff, yu, yoff, wu, woff, hu, hoff, fill, col, lwd, alpha, stroke, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed, keys) .Call(wrap__Scene__rects, self, x, y, w, h, xu, xoff, yu, yoff, wu, woff, hu, hoff, fill, col, lwd, alpha, stroke, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed, keys)

Scene$circles <- function(x, y, r, xu, xoff, yu, yoff, ru, roff, fill, col, lwd, alpha, stroke, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed, keys) .Call(wrap__Scene__circles, self, x, y, r, xu, xoff, yu, yoff, ru, roff, fill, col, lwd, alpha, stroke, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed, keys)

Scene$markers <- function(x, y, size, xu, xoff, yu, yoff, su, soff, shape, fill, col, lwd, alpha, stroke, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed, keys) .Call(wrap__Scene__markers, self, x, y, size, xu, xoff, yu, yoff, su, soff, shape, fill, col, lwd, alpha, stroke, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed, keys)

Scene$hexagons <- function(x, y, size, w, h, xu, xoff, yu, yoff, su, soff, wu, woff, hu, hoff, fill, flat, col, lwd, alpha, stroke, keys) .Call(wrap__Scene__hexagons, self, x, y, size, w, h, xu, xoff, yu, yoff, su, soff, wu, woff, hu, hoff, fill, flat, col, lwd, alpha, stroke, keys)

Scene$sectors <- function(x, y, r0, r1, theta0, theta1, xu, xoff, yu, yoff, r0u, r0off, r1u, r1off, fill, col, lwd, alpha, stroke, aangle, alen, aends, aclosed, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed, keys) .Call(wrap__Scene__sectors, self, x, y, r0, r1, theta0, theta1, xu, xoff, yu, yoff, r0u, r0off, r1u, r1off, fill, col, lwd, alpha, stroke, aangle, alen, aends, aclosed, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed, keys)

Scene$segments <- function(x0, y0, x1, y1, x0u, x0off, y0u, y0off, x1u, x1off, y1u, y1off, scap, ecap, scapu, ecapu, off, offu, col, lwd, alpha, stroke, aangle, alen, aends, aclosed, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed, keys) .Call(wrap__Scene__segments, self, x0, y0, x1, y1, x0u, x0off, y0u, y0off, x1u, x1off, y1u, y1off, scap, ecap, scapu, ecapu, off, offu, col, lwd, alpha, stroke, aangle, alen, aends, aclosed, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed, keys)

Scene$add_loop <- function(x, y, size, foot, angle, width, xu, xoff, yu, yoff, su, soff, fu, foff, col, lwd, alpha, stroke, aangle, alen, aends, aclosed) .Call(wrap__Scene__add_loop, self, x, y, size, foot, angle, width, xu, xoff, yu, yoff, su, soff, fu, foff, col, lwd, alpha, stroke, aangle, alen, aends, aclosed)

Scene$path <- function(x, y, xu, xoff, yu, yoff, nper, evenodd, fill, col, lwd, alpha, stroke, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed, key) .Call(wrap__Scene__path, self, x, y, xu, xoff, yu, yoff, nper, evenodd, fill, col, lwd, alpha, stroke, sroughness, sbowing, sfill_style, sfill_weight, shachure_angle, shachure_gap, scurve_tightness, sdisable_multi, spreserve, sseed, key)

Scene$image <- function(rgba, iw, ih, x, y, w, h, xu, xoff, yu, yoff, wu, woff, hu, hoff, interpolate) .Call(wrap__Scene__image, self, rgba, iw, ih, x, y, w, h, xu, xoff, yu, yoff, wu, woff, hu, hoff, interpolate)

Scene$text <- function(x, y, xu, xoff, yu, yoff, rot, hjust, vjust, w, h, gid, gx, gy, gsize, gpath, gface, label, family, face, size, col, alpha) .Call(wrap__Scene__text, self, x, y, xu, xoff, yu, yoff, rot, hjust, vjust, w, h, gid, gx, gy, gsize, gpath, gface, label, family, face, size, col, alpha)

Scene$texts <- function(x, y, xu, xoff, yu, yoff, rot, hjust, vjust, w, h, nper, gid, gx, gy, gsize, gpath, gface, label, family, face, size, col, alpha) .Call(wrap__Scene__texts, self, x, y, xu, xoff, yu, yoff, rot, hjust, vjust, w, h, nper, gid, gx, gy, gsize, gpath, gface, label, family, face, size, col, alpha)

Scene$texts_rich <- function(x, y, xu, xoff, yu, yoff, rot, hjust, vjust, w, h, nper, gid, gx, gy, gsize, gpath, gface, gcol, label, family, face, size, col, alpha) .Call(wrap__Scene__texts_rich, self, x, y, xu, xoff, yu, yoff, rot, hjust, vjust, w, h, nper, gid, gx, gy, gsize, gpath, gface, gcol, label, family, face, size, col, alpha)

Scene$mask_begin <- function(kind) .Call(wrap__Scene__mask_begin, self, kind)

Scene$mask_end <- function() .Call(wrap__Scene__mask_end, self)

Scene$group_start <- function(mask, alpha, blend) .Call(wrap__Scene__group_start, self, mask, alpha, blend)

Scene$group_end <- function() .Call(wrap__Scene__group_end, self)

Scene$begin_panel <- function(name) .Call(wrap__Scene__begin_panel, self, name)

Scene$end_panel <- function() .Call(wrap__Scene__end_panel, self)

Scene$subraster_start <- function(nid) .Call(wrap__Scene__subraster_start, self, nid)

Scene$subraster_end <- function() .Call(wrap__Scene__subraster_end, self)

Scene$len <- function() .Call(wrap__Scene__len, self)

Scene$dim <- function() .Call(wrap__Scene__dim, self)

Scene$dpi <- function() .Call(wrap__Scene__dpi, self)

Scene$render_png <- function(path) .Call(wrap__Scene__render_png, self, path)

Scene$render_svg <- function(path, outline_text) .Call(wrap__Scene__render_svg, self, path, outline_text)

Scene$render_svg_string <- function(outline_text) .Call(wrap__Scene__render_svg_string, self, outline_text)

Scene$render_pdf <- function(path) .Call(wrap__Scene__render_pdf, self, path)

Scene$rgba <- function() .Call(wrap__Scene__rgba, self)

Scene$content_bbox <- function() .Call(wrap__Scene__content_bbox, self)

Scene$resolved_geometry <- function() .Call(wrap__Scene__resolved_geometry, self)

Scene$element_table <- function() .Call(wrap__Scene__element_table, self)

Scene$pixel <- function(x, y) .Call(wrap__Scene__pixel, self, x, y)

Scene$hit_test <- function(x, y) .Call(wrap__Scene__hit_test, self, x, y)

#' @export
`$.Scene` <- function (self, name) { func <- Scene[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Scene` <- `$.Scene`

# nolint end
