# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib rsplot, .registration = TRUE
NULL

#' Backend identity and build info.
#'
#' A trivial call to confirm the R -> Rust path is wired up. As the backend
#' grows this will report enabled render targets and engine version.
#' @export
rs_backend_info <- function() .Call(wrap__rs_backend_info)

#' Axis-aligned bounding box of a set of points.
#'
#' Takes parallel `x`/`y` coordinate vectors and returns
#' `c(xmin, xmax, ymin, ymax)`. Representative of the kind of geometry work the
#' scene/layout engine will do; exercises borrowing R numeric vectors as slices
#' and returning a vector, with no copy on the way in.
#'
#' @param x,y Parallel numeric vectors of point coordinates.
#' @return Numeric vector `c(xmin, xmax, ymin, ymax)`, or `NULL` if empty.
#' @export
rs_bbox <- function(x, y) .Call(wrap__rs_bbox, x, y)

# nolint end
